// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BulkUpdateMode.
const (
	DELETE  BulkUpdateMode = "DELETE"
	INSERT  BulkUpdateMode = "INSERT"
	REPLACE BulkUpdateMode = "REPLACE"
	UPDATE  BulkUpdateMode = "UPDATE"
)

// BulkUpdateMode Mode of update:
//   - `INSERT` - Objects are inserted. Conflicts will cause an error.
//   - `REPLACE` - Objects are removed prior to creating if they exists.
//     All primary keys must be present in request.
//   - `UPDATE` - Objects are updated. All primary keys must be present in request.
//     Non-existent objects are ignored.
//   - `DELETE` - Objects are deleted. All primary keys must be present in request.
type BulkUpdateMode string

// BulkUpdateRequest defines model for BulkUpdateRequest.
type BulkUpdateRequest struct {
	// Mode Mode of update:
	//  * `INSERT` - Objects are inserted. Conflicts will cause an error.
	//  * `REPLACE` - Objects are removed prior to creating if they exists.
	//               All primary keys must be present in request.
	//  * `UPDATE` - Objects are updated. All primary keys must be present in request.
	//               Non-existent objects are ignored.
	//  * `DELETE` - Objects are deleted. All primary keys must be present in request.
	Mode BulkUpdateMode `json:"mode"`

	// Objects Actual data object to process
	Objects []UntypedDto `json:"objects"`
}

// ErrorObject Generic object to convey error details
type ErrorObject struct {
	// Code Code related to error state
	Code *int `json:"code,omitempty"`

	// Data Ad-hoc data associated with error
	Data *map[string]interface{} `json:"data,omitempty"`

	// Message Human readable message about error state
	Message string `json:"message"`
}

// NameList List of names, such as backends or entities
type NameList = []string

// PagedResult Paged list of items
type PagedResult struct {
	Data *[]UntypedDto `json:"data,omitempty"`

	// Offset Offset of current page from the beginning
	Offset *float32 `json:"offset,omitempty"`

	// TotalCount Total number of items matching current filter
	TotalCount *int `json:"total_count,omitempty"`
}

// UntypedDto Unstructured content, dictionary of string-to-any values.
type UntypedDto map[string]interface{}

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	// BuildTime Time when application was built
	BuildTime *string `json:"build-time,omitempty"`

	// BuildUser User who built application
	BuildUser *string `json:"build-user,omitempty"`

	// Revision VCS revision
	Revision *string `json:"revision,omitempty"`

	// Version Application version
	Version *string `json:"version,omitempty"`
}

// Backend defines model for backend.
type Backend = string

// Entity defines model for entity.
type Entity = string

// QueryNamedParams defines parameters for QueryNamed.
type QueryNamedParams struct {
	// Arg Additional arguments passed to query
	Arg *[]string `form:"arg,omitempty" json:"arg,omitempty"`
}

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// PageOffset Page offset
	PageOffset *int `form:"page-offset,omitempty" json:"page-offset,omitempty"`

	// PageSize Page size
	PageSize *int `form:"page-size,omitempty" json:"page-size,omitempty"`

	// Order List of order instructions in form of `key=direction`.
	// Key represents entity field (column) and direction is one of `ASC` or `DESC`,
	// for example `name=ASC` or `id=DESC`.
	// Direction can be omitted, in such case `ASC` is assumed.
	Order *[]string `form:"order[],omitempty" json:"order[],omitempty"`

	// Filter Filter is JSON-encoded FilterExpression.
	// Currently supported types are `simple`, `not` and `junction`.
	// Examples:
	//
	// - `{"simple": { "name": "id", "op": "=", "val" : 1}}`
	//
	//    is equivalent to SQL `id=1`
	//
	// - `{"not": { "simple": { "name": "id", "op": ">", "val" : 100}}}`
	//
	//    is equivalent to SQL `NOT (id>100)`
	//
	// - `{"junction": {"op": "AND", "sub" : [{"simple": { "name": "age", "op": ">", "val" : 35}}, {"simple": { "name": "salary", "op": ">", "val" : 5000}}]}}`
	//
	//    is equivalent to SQL `(age>35) AND (salary > 5000)`
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = UntypedDto

// BulkUpdateJSONRequestBody defines body for BulkUpdate for application/json ContentType.
type BulkUpdateJSONRequestBody = BulkUpdateRequest

// UpdateItemByIdJSONRequestBody defines body for UpdateItemById for application/json ContentType.
type UpdateItemByIdJSONRequestBody = UntypedDto

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListBackends request
	ListBackends(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersionInfo request
	GetVersionInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// QueryNamed request
	QueryNamed(ctx context.Context, backend Backend, name string, params *QueryNamedParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListEntities request
	ListEntities(ctx context.Context, backend Backend, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListItems request
	ListItems(ctx context.Context, backend Backend, entity Entity, params *ListItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateItemWithBody request with any body
	CreateItemWithBody(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateItem(ctx context.Context, backend Backend, entity Entity, body CreateItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BulkUpdateWithBody request with any body
	BulkUpdateWithBody(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BulkUpdate(ctx context.Context, backend Backend, entity Entity, body BulkUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteItemById request
	DeleteItemById(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetItemById request
	GetItemById(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExistsItemById request
	ExistsItemById(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateItemByIdWithBody request with any body
	UpdateItemByIdWithBody(ctx context.Context, backend Backend, entity Entity, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateItemById(ctx context.Context, backend Backend, entity Entity, id string, body UpdateItemByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListBackends(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBackendsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersionInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryNamed(ctx context.Context, backend Backend, name string, params *QueryNamedParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryNamedRequest(c.Server, backend, name, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListEntities(ctx context.Context, backend Backend, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEntitiesRequest(c.Server, backend)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListItems(ctx context.Context, backend Backend, entity Entity, params *ListItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListItemsRequest(c.Server, backend, entity, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateItemWithBody(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateItemRequestWithBody(c.Server, backend, entity, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateItem(ctx context.Context, backend Backend, entity Entity, body CreateItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateItemRequest(c.Server, backend, entity, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BulkUpdateWithBody(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBulkUpdateRequestWithBody(c.Server, backend, entity, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BulkUpdate(ctx context.Context, backend Backend, entity Entity, body BulkUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBulkUpdateRequest(c.Server, backend, entity, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteItemById(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteItemByIdRequest(c.Server, backend, entity, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetItemById(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetItemByIdRequest(c.Server, backend, entity, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExistsItemById(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExistsItemByIdRequest(c.Server, backend, entity, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateItemByIdWithBody(ctx context.Context, backend Backend, entity Entity, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateItemByIdRequestWithBody(c.Server, backend, entity, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateItemById(ctx context.Context, backend Backend, entity Entity, id string, body UpdateItemByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateItemByIdRequest(c.Server, backend, entity, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListBackendsRequest generates requests for ListBackends
func NewListBackendsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/backends")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVersionInfoRequest generates requests for GetVersionInfo
func NewGetVersionInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewQueryNamedRequest generates requests for QueryNamed
func NewQueryNamedRequest(server string, backend Backend, name string, params *QueryNamedParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/_query/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Arg != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "arg", runtime.ParamLocationQuery, *params.Arg); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListEntitiesRequest generates requests for ListEntities
func NewListEntitiesRequest(server string, backend Backend) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/entities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListItemsRequest generates requests for ListItems
func NewListItemsRequest(server string, backend Backend, entity Entity, params *ListItemsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.PageOffset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page-offset", runtime.ParamLocationQuery, *params.PageOffset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page-size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order[]", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "filter", runtime.ParamLocationQuery, *params.Filter); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateItemRequest calls the generic CreateItem builder with application/json body
func NewCreateItemRequest(server string, backend Backend, entity Entity, body CreateItemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateItemRequestWithBody(server, backend, entity, "application/json", bodyReader)
}

// NewCreateItemRequestWithBody generates requests for CreateItem with any type of body
func NewCreateItemRequestWithBody(server string, backend Backend, entity Entity, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewBulkUpdateRequest calls the generic BulkUpdate builder with application/json body
func NewBulkUpdateRequest(server string, backend Backend, entity Entity, body BulkUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBulkUpdateRequestWithBody(server, backend, entity, "application/json", bodyReader)
}

// NewBulkUpdateRequestWithBody generates requests for BulkUpdate with any type of body
func NewBulkUpdateRequestWithBody(server string, backend Backend, entity Entity, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/bulk", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteItemByIdRequest generates requests for DeleteItemById
func NewDeleteItemByIdRequest(server string, backend Backend, entity Entity, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetItemByIdRequest generates requests for GetItemById
func NewGetItemByIdRequest(server string, backend Backend, entity Entity, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExistsItemByIdRequest generates requests for ExistsItemById
func NewExistsItemByIdRequest(server string, backend Backend, entity Entity, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateItemByIdRequest calls the generic UpdateItemById builder with application/json body
func NewUpdateItemByIdRequest(server string, backend Backend, entity Entity, id string, body UpdateItemByIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateItemByIdRequestWithBody(server, backend, entity, id, "application/json", bodyReader)
}

// NewUpdateItemByIdRequestWithBody generates requests for UpdateItemById with any type of body
func NewUpdateItemByIdRequestWithBody(server string, backend Backend, entity Entity, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "backend", runtime.ParamLocationPath, backend)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "entity", runtime.ParamLocationPath, entity)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/%s/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListBackendsWithResponse request
	ListBackendsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBackendsResponse, error)

	// GetVersionInfoWithResponse request
	GetVersionInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionInfoResponse, error)

	// QueryNamedWithResponse request
	QueryNamedWithResponse(ctx context.Context, backend Backend, name string, params *QueryNamedParams, reqEditors ...RequestEditorFn) (*QueryNamedResponse, error)

	// ListEntitiesWithResponse request
	ListEntitiesWithResponse(ctx context.Context, backend Backend, reqEditors ...RequestEditorFn) (*ListEntitiesResponse, error)

	// ListItemsWithResponse request
	ListItemsWithResponse(ctx context.Context, backend Backend, entity Entity, params *ListItemsParams, reqEditors ...RequestEditorFn) (*ListItemsResponse, error)

	// CreateItemWithBodyWithResponse request with any body
	CreateItemWithBodyWithResponse(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateItemResponse, error)

	CreateItemWithResponse(ctx context.Context, backend Backend, entity Entity, body CreateItemJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateItemResponse, error)

	// BulkUpdateWithBodyWithResponse request with any body
	BulkUpdateWithBodyWithResponse(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BulkUpdateResponse, error)

	BulkUpdateWithResponse(ctx context.Context, backend Backend, entity Entity, body BulkUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BulkUpdateResponse, error)

	// DeleteItemByIdWithResponse request
	DeleteItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*DeleteItemByIdResponse, error)

	// GetItemByIdWithResponse request
	GetItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*GetItemByIdResponse, error)

	// ExistsItemByIdWithResponse request
	ExistsItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*ExistsItemByIdResponse, error)

	// UpdateItemByIdWithBodyWithResponse request with any body
	UpdateItemByIdWithBodyWithResponse(ctx context.Context, backend Backend, entity Entity, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateItemByIdResponse, error)

	UpdateItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, body UpdateItemByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateItemByIdResponse, error)
}

type ListBackendsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NameList
}

// Status returns HTTPResponse.Status
func (r ListBackendsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBackendsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionInfo
}

// Status returns HTTPResponse.Status
func (r GetVersionInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type QueryNamedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]UntypedDto
	JSON404      *ErrorObject
}

// Status returns HTTPResponse.Status
func (r QueryNamedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryNamedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListEntitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NameList
}

// Status returns HTTPResponse.Status
func (r ListEntitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEntitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListItemsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PagedResult
}

// Status returns HTTPResponse.Status
func (r ListItemsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListItemsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateItemResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *UntypedDto
	JSON500      *ErrorObject
}

// Status returns HTTPResponse.Status
func (r CreateItemResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateItemResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BulkUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r BulkUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BulkUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteItemByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteItemByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteItemByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetItemByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UntypedDto
	JSON404      *ErrorObject
}

// Status returns HTTPResponse.Status
func (r GetItemByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetItemByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ExistsItemByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ExistsItemByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExistsItemByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateItemByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *UntypedDto
	JSON404      *ErrorObject
}

// Status returns HTTPResponse.Status
func (r UpdateItemByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateItemByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListBackendsWithResponse request returning *ListBackendsResponse
func (c *ClientWithResponses) ListBackendsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListBackendsResponse, error) {
	rsp, err := c.ListBackends(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBackendsResponse(rsp)
}

// GetVersionInfoWithResponse request returning *GetVersionInfoResponse
func (c *ClientWithResponses) GetVersionInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionInfoResponse, error) {
	rsp, err := c.GetVersionInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionInfoResponse(rsp)
}

// QueryNamedWithResponse request returning *QueryNamedResponse
func (c *ClientWithResponses) QueryNamedWithResponse(ctx context.Context, backend Backend, name string, params *QueryNamedParams, reqEditors ...RequestEditorFn) (*QueryNamedResponse, error) {
	rsp, err := c.QueryNamed(ctx, backend, name, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryNamedResponse(rsp)
}

// ListEntitiesWithResponse request returning *ListEntitiesResponse
func (c *ClientWithResponses) ListEntitiesWithResponse(ctx context.Context, backend Backend, reqEditors ...RequestEditorFn) (*ListEntitiesResponse, error) {
	rsp, err := c.ListEntities(ctx, backend, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEntitiesResponse(rsp)
}

// ListItemsWithResponse request returning *ListItemsResponse
func (c *ClientWithResponses) ListItemsWithResponse(ctx context.Context, backend Backend, entity Entity, params *ListItemsParams, reqEditors ...RequestEditorFn) (*ListItemsResponse, error) {
	rsp, err := c.ListItems(ctx, backend, entity, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListItemsResponse(rsp)
}

// CreateItemWithBodyWithResponse request with arbitrary body returning *CreateItemResponse
func (c *ClientWithResponses) CreateItemWithBodyWithResponse(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateItemResponse, error) {
	rsp, err := c.CreateItemWithBody(ctx, backend, entity, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateItemResponse(rsp)
}

func (c *ClientWithResponses) CreateItemWithResponse(ctx context.Context, backend Backend, entity Entity, body CreateItemJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateItemResponse, error) {
	rsp, err := c.CreateItem(ctx, backend, entity, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateItemResponse(rsp)
}

// BulkUpdateWithBodyWithResponse request with arbitrary body returning *BulkUpdateResponse
func (c *ClientWithResponses) BulkUpdateWithBodyWithResponse(ctx context.Context, backend Backend, entity Entity, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BulkUpdateResponse, error) {
	rsp, err := c.BulkUpdateWithBody(ctx, backend, entity, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBulkUpdateResponse(rsp)
}

func (c *ClientWithResponses) BulkUpdateWithResponse(ctx context.Context, backend Backend, entity Entity, body BulkUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*BulkUpdateResponse, error) {
	rsp, err := c.BulkUpdate(ctx, backend, entity, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBulkUpdateResponse(rsp)
}

// DeleteItemByIdWithResponse request returning *DeleteItemByIdResponse
func (c *ClientWithResponses) DeleteItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*DeleteItemByIdResponse, error) {
	rsp, err := c.DeleteItemById(ctx, backend, entity, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteItemByIdResponse(rsp)
}

// GetItemByIdWithResponse request returning *GetItemByIdResponse
func (c *ClientWithResponses) GetItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*GetItemByIdResponse, error) {
	rsp, err := c.GetItemById(ctx, backend, entity, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetItemByIdResponse(rsp)
}

// ExistsItemByIdWithResponse request returning *ExistsItemByIdResponse
func (c *ClientWithResponses) ExistsItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, reqEditors ...RequestEditorFn) (*ExistsItemByIdResponse, error) {
	rsp, err := c.ExistsItemById(ctx, backend, entity, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExistsItemByIdResponse(rsp)
}

// UpdateItemByIdWithBodyWithResponse request with arbitrary body returning *UpdateItemByIdResponse
func (c *ClientWithResponses) UpdateItemByIdWithBodyWithResponse(ctx context.Context, backend Backend, entity Entity, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateItemByIdResponse, error) {
	rsp, err := c.UpdateItemByIdWithBody(ctx, backend, entity, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateItemByIdResponse(rsp)
}

func (c *ClientWithResponses) UpdateItemByIdWithResponse(ctx context.Context, backend Backend, entity Entity, id string, body UpdateItemByIdJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateItemByIdResponse, error) {
	rsp, err := c.UpdateItemById(ctx, backend, entity, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateItemByIdResponse(rsp)
}

// ParseListBackendsResponse parses an HTTP response from a ListBackendsWithResponse call
func ParseListBackendsResponse(rsp *http.Response) (*ListBackendsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBackendsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NameList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetVersionInfoResponse parses an HTTP response from a GetVersionInfoWithResponse call
func ParseGetVersionInfoResponse(rsp *http.Response) (*GetVersionInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseQueryNamedResponse parses an HTTP response from a QueryNamedWithResponse call
func ParseQueryNamedResponse(rsp *http.Response) (*QueryNamedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryNamedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []UntypedDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListEntitiesResponse parses an HTTP response from a ListEntitiesWithResponse call
func ParseListEntitiesResponse(rsp *http.Response) (*ListEntitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEntitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NameList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListItemsResponse parses an HTTP response from a ListItemsWithResponse call
func ParseListItemsResponse(rsp *http.Response) (*ListItemsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListItemsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PagedResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateItemResponse parses an HTTP response from a CreateItemWithResponse call
func ParseCreateItemResponse(rsp *http.Response) (*CreateItemResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateItemResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest UntypedDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseBulkUpdateResponse parses an HTTP response from a BulkUpdateWithResponse call
func ParseBulkUpdateResponse(rsp *http.Response) (*BulkUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BulkUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDeleteItemByIdResponse parses an HTTP response from a DeleteItemByIdWithResponse call
func ParseDeleteItemByIdResponse(rsp *http.Response) (*DeleteItemByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteItemByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetItemByIdResponse parses an HTTP response from a GetItemByIdWithResponse call
func ParseGetItemByIdResponse(rsp *http.Response) (*GetItemByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetItemByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UntypedDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseExistsItemByIdResponse parses an HTTP response from a ExistsItemByIdWithResponse call
func ParseExistsItemByIdResponse(rsp *http.Response) (*ExistsItemByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExistsItemByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUpdateItemByIdResponse parses an HTTP response from a UpdateItemByIdWithResponse call
func ParseUpdateItemByIdResponse(rsp *http.Response) (*UpdateItemByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateItemByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest UntypedDto
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all configured backends
	// (GET /backends)
	ListBackends(w http.ResponseWriter, r *http.Request)
	// Get version info
	// (GET /version)
	GetVersionInfo(w http.ResponseWriter, r *http.Request)
	// Execute named query and return the result set
	// (GET /{backend}/_query/{name})
	QueryNamed(w http.ResponseWriter, r *http.Request, backend Backend, name string, params QueryNamedParams)
	// List all known entities within backend
	// (GET /{backend}/entities)
	ListEntities(w http.ResponseWriter, r *http.Request, backend Backend)
	// List entity items
	// (GET /{backend}/{entity})
	ListItems(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity, params ListItemsParams)
	// Create new entity item
	// (POST /{backend}/{entity})
	CreateItem(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity)
	// Perform bulk update
	// (POST /{backend}/{entity}/bulk)
	BulkUpdate(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity)
	// Delete entity item by ID
	// (DELETE /{backend}/{entity}/{id})
	DeleteItemById(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity, id string)
	// Get entity item by ID
	// (GET /{backend}/{entity}/{id})
	GetItemById(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity, id string)
	// Check for existence of entity item by ID
	// (HEAD /{backend}/{entity}/{id})
	ExistsItemById(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity, id string)
	// Update entity item in-place by ID
	// (PUT /{backend}/{entity}/{id})
	UpdateItemById(w http.ResponseWriter, r *http.Request, backend Backend, entity Entity, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBackends operation middleware
func (siw *ServerInterfaceWrapper) ListBackends(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBackends(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersionInfo operation middleware
func (siw *ServerInterfaceWrapper) GetVersionInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersionInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryNamed operation middleware
func (siw *ServerInterfaceWrapper) QueryNamed(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", mux.Vars(r)["name"], &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryNamedParams

	// ------------- Optional query parameter "arg" -------------

	err = runtime.BindQueryParameter("form", true, false, "arg", r.URL.Query(), &params.Arg)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "arg", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryNamed(w, r, backend, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEntities operation middleware
func (siw *ServerInterfaceWrapper) ListEntities(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEntities(w, r, backend)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "page-offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-offset", r.URL.Query(), &params.PageOffset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-offset", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	// ------------- Optional query parameter "order[]" -------------

	err = runtime.BindQueryParameter("form", true, false, "order[]", r.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order[]", Err: err})
		return
	}

	// ------------- Optional query parameter "filter" -------------

	err = runtime.BindQueryParameter("form", true, false, "filter", r.URL.Query(), &params.Filter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filter", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, backend, entity, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r, backend, entity)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BulkUpdate operation middleware
func (siw *ServerInterfaceWrapper) BulkUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BulkUpdate(w, r, backend, entity)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItemById operation middleware
func (siw *ServerInterfaceWrapper) DeleteItemById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItemById(w, r, backend, entity, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetItemById operation middleware
func (siw *ServerInterfaceWrapper) GetItemById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetItemById(w, r, backend, entity, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExistsItemById operation middleware
func (siw *ServerInterfaceWrapper) ExistsItemById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExistsItemById(w, r, backend, entity, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItemById operation middleware
func (siw *ServerInterfaceWrapper) UpdateItemById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backend" -------------
	var backend Backend

	err = runtime.BindStyledParameterWithOptions("simple", "backend", mux.Vars(r)["backend"], &backend, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backend", Err: err})
		return
	}

	// ------------- Path parameter "entity" -------------
	var entity Entity

	err = runtime.BindStyledParameterWithOptions("simple", "entity", mux.Vars(r)["entity"], &entity, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItemById(w, r, backend, entity, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/backends", wrapper.ListBackends).Methods("GET")

	r.HandleFunc(options.BaseURL+"/version", wrapper.GetVersionInfo).Methods("GET")

	r.HandleFunc(options.BaseURL+"/{backend}/_query/{name}", wrapper.QueryNamed).Methods("GET")

	r.HandleFunc(options.BaseURL+"/{backend}/entities", wrapper.ListEntities).Methods("GET")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}", wrapper.ListItems).Methods("GET")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}", wrapper.CreateItem).Methods("POST")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}/bulk", wrapper.BulkUpdate).Methods("POST")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}/{id}", wrapper.DeleteItemById).Methods("DELETE")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}/{id}", wrapper.GetItemById).Methods("GET")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}/{id}", wrapper.ExistsItemById).Methods("HEAD")

	r.HandleFunc(options.BaseURL+"/{backend}/{entity}/{id}", wrapper.UpdateItemById).Methods("PUT")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra23LbONJ+FRT+/yKzS53syV6oKheOpM1o1+t4fMiN5YogoiUiJgEOAErWqPjuWw2Q",
	"EiVStnNwatY3NkmgD193f2gA3tBQJamSIK2h/Q1NmWYJWNDuacbCB5Ac/+RgQi1SK5SkfXrBEiBqTooB",
	"xCoyBxtGBKQVVoAhc60SGlCBo1NmIxpQyRKg/a3QgGr4IxMaOO1bnUFATRhBwlBbwh7PQS5sRPv/OA1o",
	"ImT52AtQnAWNgu8mk9Xn1v3faUDtOkXhxmohFzTPA+pMWR+3vfjeaOP222uamJfiHNbvs/jhNuXMwn8U",
	"h7rZ+BbNztyY/kSSv5Hp+OJ6dHUzJS3ycfYFQmsI00CENKAt8DYZKDmPBb5fiTgmIcsMECYJaK1028u4",
	"Gl2enw1Gh0I0JGoJnKRaKI0BDjUwK+SCiDmxEawJPApjDUrZ+zmLY5yUML0mD7A2JMmMJTMgqQYD0hIh",
	"CcIKxhYW3F4Oz25qBnhHeftrBe79XCjZcnbiOFXFaCGVBl5YMBydj+oWcIjhGyygmHtZQvt31MeHBrQA",
	"mQbUO0sD6nXS+1piBJVcuPJSXWlqlYLG4nLpVyTJ/2uY0z79v86ujjtFVnUOUioPaIFAPbvOQpuxmHBm",
	"WQEThjzVKgRjsEYsJOY5fbcSPeFDq1BXIuTYz+ptXWRas7Wrzl1h3XlfdsbtEPFvUNgIE9bHpm78B5Cg",
	"RVgxPFRyiRmKswgHy0SMXuxDGDbW2QDrTEOMuYeivAxjmYVdDQtpYQGaBvSxtVCt3Vu0FUFEuYxzgUJZ",
	"fFnR63nkAH3eilTo0WfGqFA47SthI6/f4QnGsEWDxb9lCcP8Y5zNYiDFOMJmKrPN5ldYci8OhYb7PHAs",
	"eS5MA9r4FokIqdIExGRhRJgplwJDlN6uAtXEqSX5fkoE9JItgF+ByeIGpe4jiQvVXuhhPEvcvyFXD21R",
	"87mBBjM+uvdoQphpjZWfItS42CEnkhkshJTo4FamzJIZuABaZVn8OVSZbJB8gx+JH7x1kSTMhhFybqlu",
	"LmLr8u4gEfO8oWgqPn5VOt5KY3UW2kwDx1JC8gwIF6Gbrtdon49jy6oWk2uyZHEGpk0bjPgE2gglx3Ku",
	"6iw2y0TMW1YkDWl9IxIgqwgkYWkai5Dhe7LCVMtEbGkDb3pxmQFdF3drQJNVpPzsqswmSRqWwriJh3I+",
	"Da7J9mvDzKX3t4FiK16Ug5oq8gBBfCUK8A5qAvRc6YQMrm6HBFH1stmCCWmsY5MZM7CrzMxgKl2Nrm/I",
	"2eUYoxWLEKRx4Bedz1nKwgjISbtLA5rpmPZpZG1q+p3OarVqM/e5rfSiU8w1nfPxYHRxPWqdtLvtyCax",
	"y3VhYxQ3LI2waquYzLTgC6SjLVZ02Wt3211XeilIlgrap6ftbvuUumYqctnSKT3BhwU0rgR2SxIMGx4l",
	"52Lh8ng716nwWI15wWfvdx81mFShXyj9pNv1K4WrAVdFuyh2vhgf511T+BTjbBnVhbSZU4/Z7HrFLMEG",
	"pBx93D3LFgbpvGy073F2p5KXR6Eza2MhKbOTuLQ7hOsD2GpJvyJgVTUNmH2qWrkPEPpy4EQJinv0iGwK",
	"gPLO5z8y0OvOBmsgryC07/nvOAijyL/X6+9eoepoOOMIPEKYYevAJPfthAabaQkcZfza/fWHBafakDWY",
	"U26yHLBEGCKVJRpCtZDiT7RmL14jb7ZrKXgxBz3wxruVVbvGgOCqnAd729S7ZkN3Q0raoHmwedJM7LeE",
	"V1dWVrlANOwR3a+ndog1aq+tCNsVmTC9yBK0m6TMGN95OqNK3eVDoZxpbDEaMuqZNiu/38/8baf2EkZ9",
	"kGold1v8Aq6FWIIku119nV1Hu3bwGwN3/xfg5Zd4f4Snm6fuICvJqTh2OKSnjX+fHw2SU+QHFY2jX+pT",
	"rZaCYxOnhQUtWGN4xmU3vR+begNOira4OSWxE25tR1QOSoQUCW6Hu01da6MeI/6Ep7QU3/cOY7yOXrcb",
	"7DT2XqKxjLHSHDQRRe8rlDS4rXcdlpqT6QOs33GhwX2atify37AmGooTAFPCPxcQc/ImVHGWyF88D5ez",
	"kAeVdIQzPbseTHGrNB2OrgfTYCLnuG96ZEkaA5mis++2QwR/50a1J3K4lRUySWZAVCKsBR6grW4rFmK3",
	"5cULg7vJLHHHHEfwdF7f3X8bmdSw/KfbnqDif11/vGiBxD02J/716BHBwkW5PZEDv6GJ18Rkaaq0222v",
	"U/AnL1MjEIhpQKZS2amDcfolk1vwRx4p05/IiWyR6WZC/ZQJ7ZMNmTj38O8JFXxCAzKhKvXP7/zjksUT",
	"Svqkl+dTFEIImo1kvmQxbrWsIte/nzv0e9OdGqlsqeOlGidZt3sKB2q73fw5zRcfb8gbwf30Xrf7S8WM",
	"Egynfafq7GLo9Zhs5vTcPYEMW8Dzhp6+zfOAPCHFsJjp9fOC3nbR5fvnnH6DVrnpp29/IWcXQ/LGayD+",
	"rZODSBxJ6O0O+fhC/JqrSfUU44kFxZdYw3JRZfHKyhDqjLtzmW/vfJ4ZWqw9CE6qTEP7O9DALOBiUXQ9",
	"YOx7xdc/DLpqw1tHbuBV7E7uHUbbg2nwu/a9qPZ+lmnOAE6GNx99m/224VjRjSk7YRbHagW8jcPf/sDs",
	"e6Yrv5XuhHCLWXkHsp+HhakSVlWk68nY3KR0Zln8cHiV9HMzdXfu/UqZWj+fz/M8b2aV/QjgzMpZDcp2",
	"dwy4dodgzDyL43UlK/Znj6UFjdsFf6q7ikQM5SE99nszZsPoIJrlKRGGpbhTeXEoN4Ln3go0sg700L1H",
	"Sni/Hjfsin9tcAGLdsVMeb/UPloxXni9Yva8KwZVGWG2JuNhE3U2buo/gD1uf/cnEcioUmY/d5/uwyFs",
	"VGxkxkPCFXjI3b3Z0fBcAePPBAf3ji+KTASM10MzcveLX59dxb1kBcmv9Ln9PU4PIggfiO/m3b1jCIdr",
	"1lEcXp0yaw37eHhgXPNZh3jt63rk8qyhPD3L7uXAX6fxKNi0TvwnP8k0jw7fi9//Cn94258ppmJQFXch",
	"W2nMQjhWRU4A6GVZRP4OY5NqZVWo4rzf6WwiZWze3+C2M++wVHSWPRrQJdMC+yMXxEiVd59z5m4kaaxC",
	"FrvXhyD8poyVxUni2eWYePWORVDFvpiTk263VxNxqbQlSuKSHkYVIYhP7GhEyIWXWDiyLzWyNq0JvYlc",
	"d+CGO0ZiYdkp2Aj8HVDuaq/AsNatFP/eU16Hb2vT1P+dp84txar21OSjvLR/p1WZ4aLcwGMSmxxWnKY2",
	"TfTXBPf5fwMAAP//I/r+HfIkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
